name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: ${{ startsWith(matrix.kotlin-version, '1.4') }}

    strategy:
      # Run all tasks, even if some fail. Note that they don't share an output, some tasks overlap
      # which is expected. If they need to share their outputs, then we need a proper caching
      # solution.
      fail-fast: false
      matrix:
        gradle-task: [assemble, test, lint, ktlintCheck]
        kotlin-version: [1.3.72, 1.4-M2]

    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: ${{ matrix.gradle-task }} with Gradle
        run: ./gradlew ${{ matrix.gradle-task }} --no-build-cache --no-daemon --stacktrace

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macos-latest
    timeout-minutes: 20
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        api-level:
          # Consider other devices in case it's needed.
          #- 24
          - 29
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          script: ./gradlew connectedCheck --no-build-cache --no-daemon --stacktrace

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: insrumentation-test-results
          path: ./**/build/reports/androidTests/connected/**
